# Generated by Django 2.0.5 on 2021-11-01 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('draft', 'Проект'), ('published', 'Опубликовано')], default='draft', max_length=10),
        ),
    ]
