# Generated by Django 3.2.8 on 2021-11-07 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20211105_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('draft', 'Отложено'), ('published', 'Опубликовано')], default='draft', max_length=10),
        ),
    ]
